### ISSUE TITLE
[BUG] adding a category with the character "_" in the name prevents the creation of the group "datamanager-"

### ISSUE THREAD

**Issue by ccacciari** [UtrechtUniversity/yoda-ansible#106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I created a new category from the Yoda Group Manager tab with the related sub-category.
The category name is "surf_test2" and the sub-categroy name is "surf_test2".
When I check the option to add the datamanager group, the option is not there.

![image](https://user-images.githubusercontent.com/7924423/151850861-31a82e4f-63b0-422c-b9a2-f255a09e8923.png)

### Expected Behavior

I would expect to have the option "datamanager-" listed among the other options.

![image](https://user-images.githubusercontent.com/7924423/151852154-52c97ff3-2040-4a34-9518-bd067dfab733.png)

### Steps To Reproduce

1. Log in to Yoda (tested with both: privileged user in System categories "priv-category-add" and "priv-group-add", and surfadmin)
2. Got to the Group Manager tab
3. Click on the button "add Group"
4. Add the name of a new category containing the character "_"
5. Add the name of a subcategory
6. Open the list of the prefixes for the group and search for "datamanager-"

### Environment

```markdown
- Yoda: 1.7 and 1.8
- Operating System: CentOS 7
- Browser: Firefox and Safari latest versions
```

**Comment by lwesterhof** [comment]
We do not allow underscores in group names, only lowercase letters, numbers and hyphens. The datamanager group always has the same name as the category. When the category name contains an underscore the option to create a datamanager group is removed, because the datamanager group would be invalid.

**Comment by ccacciari** [comment]
I see. But then my request is to
- make this constraint more evident in the documentation
- add a mechanism to prevent the user from creating a category with the character "_", a validation of the text field with a clear error message in case of wrong characters.

**Comment by Danny-dK** [comment]
This is also true for capital letters in the category name. When I added as a test WUR-library as a category, the data manager group was also not visible, but no warning was given.

**Comment by Danny-dK** [comment]
Oh, I just saw #25 which may be why I encountered it as I was recently given rodsadmin.

**Comment by lwesterhof** [comment]
Issue #25 was fixed by https://github.com/UtrechtUniversity/yoda-ruleset/commit/308e376d416567b61d2b43022163fa88d1896528
