### ISSUE TITLE
[BUG] the second time a new user is added to a group, the link "Click here to add a new user to this group" disappears

### ISSUE THREAD

**Issue by ccacciari** [UtrechtUniversity/yoda-ansible#108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I add a user to a group, clicking on the link "Click here to add a new user to this group" in the Group Manager tab.
It works fine. Then I try to add a second user to the same group clicking on the same link. However after I click on it, the link disappears and the only way to make it appears again is refreshing the page.

### Expected Behavior

I would expect that the link is always visible, no matter how many users I add, one after another.

### Steps To Reproduce

- Log in to the Yoda Portal
- click on the link "Click here to add a new user to this group" in the Group Manager tab.
- enter a new username (email)
- click on the add button
- click on the link "Click here to add a new user to this group" again.
- the link disappears
- a search field appears in the top left corner of the page
![image](https://user-images.githubusercontent.com/7924423/152514645-c82cf37e-7aaf-4d41-84e0-190f72badd79.png)

### Environment

```markdown
- Yoda: 1.8
- Operating System: CentOS7
- Browser: Firefox 96.0.3 (64-bit)
```

**Comment by lwesterhof** [comment]
Tracking internally as YDA-4519.
