### ISSUE TITLE
[BUG] error message when you click on the "Update" button of a group without changing anything

### ISSUE THREAD

**Issue by ccacciari** [UtrechtUniversity/yoda-ansible#109]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I click on the button "Update" in the Group Manager tab without changing any value in the form, I get an error message: "Error: Could not update group due to an internal error. Please contact a Yoda administrator".
It is misleading: there should be no error since nothing is changed. 

### Expected Behavior

I would expect no error message.

### Steps To Reproduce

1. Log in the Yoda portal,
2. select a group in the tab Group Manager,
3. click on the button "Update"
4. a pop up window with an error message appears: "Error: Could not update group due to an internal error. Please contact a Yoda administrator"

![image](https://user-images.githubusercontent.com/7924423/152774080-a74dfc80-2ae8-413f-adb4-f8c2318047c7.png)

### Environment

```markdown
- Yoda: 1.8
- Operating System: CentOS7
- Browser: Firefox 96.0.3 (64-bit)
```

**Comment by stsnel** [comment]
Thanks for the bug report. We can reproduce this issue and have assigned it internal ticket number YDA-4521.
