### ISSUE TITLE
[FEATURE] Check ORCID for correctness in metadata form

### ISSUE THREAD

**Issue by erikvdbergh** [UtrechtUniversity/yoda-ansible#135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When entering an orcid in the metadata form, any value can be entered. 

![afbeelding](https://user-images.githubusercontent.com/13100497/181463419-978160aa-438a-429e-96da-4e175d3b09eb.png)

### Expected Behavior

To prevent errors, it would be good to have a front end check against the standard orcid format (e.g. 0000-0001-2345-6789).

### Steps To Reproduce

1. In yoda 1.7, create a folder
2. Enter the metadataform
3. In the Creator->Person identifier section, select ORCid for the person identifier
4. Enter any value and save

### Environment

```markdown
- Yoda: 1.7
- Ansible: don't know
- Operating System:
- Browser: Firefox
```

**Comment by lwesterhof** [comment]
Tracking this issue in our internal bug tracker as ticket YDA-4759.

**Comment by jjkoehorst** [comment]
It would be great if the JSON can have REGEX values in there to which the value should conform.
For example the orcid regex is ^\d{4}-\d{4}-\d{4}-\d{3}(\d|X)$ according to https://registry.identifiers.org/registry/orcid

**Comment by lwesterhof** [comment]
> It would be great if the JSON can have REGEX values in there to which the value should conform. For example the orcid regex is ^\d{4}-\d{4}-\d{4}-\d{3}(\d|X)$ according to https://registry.identifiers.org/registry/orcid

You can add this to your metadata schema as a custom type. JSON schema has support for regular expressions: https://json-schema.org/understanding-json-schema/reference/regular_expressions.html

Note that the regex is not conform the specification of ORCID, it should include the full https URI: https://support.orcid.org/hc/en-us/articles/360006897674-Structure-of-the-ORCID-Identifier
