### ISSUE TITLE
dynamic 'group properties' and 'group members' boxes placement

### ISSUE THREAD

**Issue by Danny-dK** [UtrechtUniversity/yoda-ansible#137]
#### Is your feature request related to a problem? Please describe.
I have a long list of categories in Yoda@WUR. When adding groups to a category all the way down, I have to scroll all the way up to add people and / or see group properties. 

#### Describe the solution you'd like
Within the webportal in the group manager section, is it possible to have the boxes group properties and group members be dynamic in position allowing to move automatically as you scroll down? At Yoda@WUR I have so many categories that I'm scrolling quite a bit down for a certain category to add a group and then scrolling all the way up to add someone. This is not problematic if you only have one group to add people to, but creating several research groups and adding different people to each group is a lot of up and down scrolling. It is also a bit cumbersome when you can't immediately see the group properties and party members of that group when you specifically want to know which people have access to certain groups in a category all the way down on a long list.

#### Describe alternatives you've considered
Maybe a slide combo box when clicking on a group instead of moving the group properties and group members boxes during scrolling.

**Comment by lwesterhof** [comment]
Good idea, something like this?

https://user-images.githubusercontent.com/29246264/182334359-ee2524e0-c103-4839-995e-670f5d20770a.mp4

**Comment by Danny-dK** [comment]
wait ... (″･ิ_･ิ)っ you already done it... you're a wizard... (∩｀-´)⊃━☆ﾟ.*･｡ﾟ 

Exactly like that.
