### ISSUE TITLE
Menu always to foreground

### ISSUE THREAD

**Issue by Danny-dK** [UtrechtUniversity/yoda-ansible#157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am very happy with #137 since we updated to Yoda 1.8. It is only a minor inconvenience, but would it be possible to have the right corner top menu to be forced to the front?

Right now the menu is behind the new dynamic group properties,:

![image](https://user-images.githubusercontent.com/45395070/191827564-285c194f-259d-4212-a7f0-0bb7b1d7db82.png)

It currently hides the other options that are visible in the other areas of Yoda (research, vault):

![image](https://user-images.githubusercontent.com/45395070/191827826-dbb83a6e-945f-44cb-9ad5-01d714755646.png)

### Expected Behavior

have the right top corner menu always to the front of the screen.

### Steps To Reproduce

- go the group manager section
- click on the right top corner menu (on your name)
- not all fields are visible

### Environment

```markdown
- Yoda: 1.8
- Browser: Chrome 105.0.5195.127 (64-bit) and FireFox 105.0 (64-bit)
- Operating System: Windows 10
```

**Comment by lwesterhof** [comment]
This has been fixed in v1.8.2: https://github.com/UtrechtUniversity/yoda-portal/commit/a1d7e9bfa126ad4a6edf1879455fd437da932ea1

![Screenshot 2022-09-23 at 09-29-24 Yoda - Dev ‐ Group Manager](https://user-images.githubusercontent.com/29246264/191911753-517c54c4-52b5-4a8f-8b1d-15b9846c7040.png)
