### ISSUE TITLE
[FEATURE] Affiliation identifier field

### ISSUE THREAD

**Issue by Danny-dK** [UtrechtUniversity/yoda-ansible#160]
#### Is your feature request related to a problem? Please describe.
The affiliation field in the metadata form is a free text form that invites different types of spelling of affiliation (such as UU, Utrecht University; or WUR, Wageningen UR, Wageningen University and Research, Wageningen University & Research, Wageningen University, etc). Although a person identifier can be provided, an affiliation identifier is not present. 

#### Describe the solution you'd like
Please consider an affilliation identifier to be able to be filled in such as a ROR ID 
https://ror.org/
https://ror.org/04pp8hn57

That way affiliation can be more uniformly provided instead of relying on the proper spelling. 

#### Describe alternatives you've considered
None. Other affiliation ID's are less suited see https://ucd-library.github.io/ror-extend-demo/ at alternatives at bottom of page.

**Comment by peer35** [comment]
+1 This is supported in DataCite since version 4.3 http://schema.datacite.org/meta/kernel-4.3/

**Comment by stsnel** [comment]
Thanks for the input. This feature request was accepted in the 25 October 2022 data manager meeting. We're now tracking it as ticket YDA-4893.

**Comment by lwesterhof** [comment]
Support for (ROR) identifiers has been added in https://github.com/UtrechtUniversity/yoda-portal/pull/189 and https://github.com/UtrechtUniversity/yoda-ruleset/pull/267.
