### ISSUE TITLE
[BUG] changing the subcategory in group properties for a datamanager group does not work

### ISSUE THREAD

**Issue by ccacciari** [UtrechtUniversity/yoda-ansible#172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to changing the subcategory of an existing datamanger group, I got this error:

![image](https://user-images.githubusercontent.com/7924423/201052467-931373e3-5636-440d-acab-3a7864e65b58.png)

### Expected Behavior

The subcategory name should be updated.

### Steps To Reproduce

1. Log in to Yoda web portal
2. go to the Group manager panel
3. Edit an existing datamanager group
4. Change the subcategory name
5. Click on the button "update"

### Environment

```markdown
- Yoda: 1.8.4 patched with https://github.com/UtrechtUniversity/yoda-portal/commit/a5df2cc9efc0ddc04115044b2d1da06893acf298
- Ansible:
- Operating System: centos7
- Browser: Firefox 106.0.1
```

### Anything else?

I have not tested yet if it applies to Yoda v1.8.5

**Comment by stsnel** [comment]
Thanks for the bug report. We can replicate the issue in 1.8.5 and are tracking it in the internal issue tracker as _YDA-4967_.
