### ISSUE TITLE
[FEATURE] support for subdomain in ansible parameter external_users_domain_filter and oidc_domains

### ISSUE THREAD

**Issue by ccacciari** [UtrechtUniversity/yoda-ansible#173]
The configuration for OIDC domains works only for the root domain, for example surf.nl.
If the organization has users with emails with subdomains, they are not matched by the current Yoda rules.
For example mydepartment.surf.nl is not matched if the oidc_domains list contain surf.nl.

I would like that the subdomains are automatically matched.
Using a jolly character would also be fine for me, for example: "*.surf.nl".

So far, I have added explicitly the subdomains in the list, for example:  "mydepartment.surf.nl | surf.nl".
But that solution does not scale well and it is less robust in case of changes in the subdomains of an organization.

**Comment by lwesterhof** [comment]
Thanks for the input. We're now tracking it as ticket YDA-4934.
