### ISSUE TITLE
[FEATURE] statistics overview split between reserach, vault, and total used.

### ISSUE THREAD

**Issue by Danny-dK** [UtrechtUniversity/yoda-ansible#174]
#### Is your feature request related to a problem? Please describe.
The statistics module shows total used storage by category and group. But no distinction is possible between research area, vault area, and total used storage. 

#### Describe the solution you'd like
A selection button within the statistics module to select either amount of data stored in the research area, amount of data stored in the vault area, or total (research+vault). The exported file would then need to be adjusted according to the selection or all could be exported within the file where the column groupname would need a distinction between research and vault. Preferably also a selection of time period would be nice. (perhaps even something in line of a flexible interactive dashboard to filter various aspects (Rshiny example https://ceefluz.shinyapps.io/radar/) , but a distinction for now would already be nice).

#### Describe alternatives you've considered
Could query with iCommands, but as Yoda is increasingly being used by other institutes, we\they need an easy GUI to assess how much data is being stored in their instance to keep track of storage and associated costs per group / category. It would also help in keeping track of whether people are actually using the vault according to policy to archive data.

**Comment by lwesterhof** [comment]
Thanks for the input. We're now tracking it as ticket YDA-4933.
