### ISSUE TITLE
[FEATURE] Value of DataCite Publisher field should be configurable

### ISSUE THREAD

**Issue by peer35** [UtrechtUniversity/yoda-ansible#188]
#### Is your feature request related to a problem? Please describe.
When we publish a dataset the value of the Publisher field in the DataCite metadata is set to "Utrecht University". In our case this should be "Vrije Universiteit Amsterdam"
A quick search suggests the Publisher value is set in https://github.com/UtrechtUniversity/yoda-ruleset/blob/release-1.8/json_datacite41.py lines 153-155
```
def get_publisher(combi):
    # FIXME (untouched from b057f496).
    return 'Utrecht University'
```
This can't be changed at all by us and is difficult to change for SURF.

#### Describe the solution you'd like
The value generally will seldom or never change for an institution, so a way to set the value during installation or upgrades would be fine.

Another option could be to set it as a default value in the metadata schema. That way it could be changed by a rodsadmin at an institution.

#### Describe alternatives you've considered
For now we can change the value in DataCite Fabrica, but this is of course not ideal.

**Comment by lwesterhof** [comment]
Thanks for the report. We're now tracking it as ticket YDA-4973.
