### ISSUE TITLE
[BUG] DataCite metadata contains an incorrect date field.

### ISSUE THREAD

**Issue by peer35** [UtrechtUniversity/yoda-ansible#189]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

See DOI 10.48338/vu01-2lt5v4
The metadata contains a Date field with "Date Type" "Updated". This was set to `2022-12-08Y11:57.46.000000`.  

When you try to update the dataset in DataCite Fabrica you can't update the DOI and it shows an error message stating:
"To save this DOI, first resolve the errors with these properties: date."

This field is not in the Yoda metadata so is probably automatically set in the Yoda to DataCite conversion.

Removing the decimals `2022-12-08Y11:57.46` resolves the issue.

### Expected Behavior

Dates should be correctly formatted.

### Steps To Reproduce

1. Find the DOI in DataCite fabrica https://doi.datacite.org/dois/10.48338%2Fvu01-2lt5v4
2. Click "Update DOI (Form)"
3. The "Update DOI" button is greyed out and the error message shown:
![image](https://user-images.githubusercontent.com/5236397/207290185-bc159662-8dd1-449a-ad98-efa45328e9db.png)

The date fields: 
![image](https://user-images.githubusercontent.com/5236397/207290231-2171b133-3fa2-4557-827d-5db429c598b0.png)

### Environment

```markdown
- Yoda: 1.8
- Ansible: -
- Operating System: -
- Browser: -
```

**Comment by lwesterhof** [comment]
Thanks for the report. We're now tracking it as ticket YDA-4974.
