### ISSUE TITLE
[BUG] Removing all Contributor or Identifier blocks generates a confusing Validation warning

### ISSUE THREAD

**Issue by peer35** [UtrechtUniversity/yoda-ansible#194]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This one was reported by one of our researchers. 

- He had added a few names as Contributors, but on second thought wanted those names as Creators. So he copied the Contributors info and deleted all the Contributors. 
- Because he didn't know any identifiers of these Creators he decided to also delete the Identifier blocks of the newly added Creators.

When he tried to save the metadata form threw validation warnings:
".Contributor should NOT have fewer than 1 items". 
".Creator[0].Person_Identifier should NOT have fewer than 1 items"

Which incorrectly led him to believe that he should always have at least one Contributor and one Identifier for each Contributor or Creator.

### Expected Behavior

The metadata form should either disallow removing all Contributor or Identifier "blocks" in the form or silently add an empty block on saving.

### Steps To Reproduce

1. Open the metadata form in any folder.
2. Remove all Contributor blocks by clicking on the trashcan. 
3. The Contributor block only shows the help text and a plus sign.
![Pasted image 20221222160642](https://user-images.githubusercontent.com/5236397/209167734-1ad09352-8bd8-48da-86ef-0db826785896.png)
4. Now click save. 
5. The form shows validation warnings: ".Contributor should NOT have fewer than 1 items". 
![Pasted image 20221222160823](https://user-images.githubusercontent.com/5236397/209168003-4ed95f75-f864-4725-9cf8-f0cc570902aa.png)
This gives the researcher the idea that adding one contributor is always mandatory, but it is not. Clicking the plus sign to add an empty Contributor block solves the issue, but this is counterintuitive.

- The same thing happens when you delete all person identifier blocks from a creator or contributor block:
".Creator[0].Person_Identifier should NOT have fewer than 1 items"
![Pasted image 20221222161110](https://user-images.githubusercontent.com/5236397/209168296-786efc0d-9738-4e46-98cd-2514c5db409d.png)

Again this gives the impression that the researcher should always add an identifier, but this is not mandatory.

### Environment

```markdown
- Yoda: 1.8
- Ansible:
- Operating System:
- Browser:
```

**Comment by stsnel** [comment]
Internal bug tracker ticket: YDA-4828
