### ISSUE TITLE
[BUG] irods resource installation hangs due to wrong pip version

### ISSUE THREAD

**Issue by fj-morales** [UtrechtUniversity/yoda-ansible#210]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When installing an irods resource server (in a different host from the icat server), the installation process stop at the step: 

TASK [yoda_ruleset : Install requirements for ruleset]

with a pip error (v8.1.2, which seems to be the default with Centos 7)

### Expected Behavior

This error should not occur and the installation should continue.

It seems that the file https://github.com/UtrechtUniversity/yoda/blob/development/roles/irods_resource/meta/main.yml misses the dependency task:

dependencies:
  - python_irodsclient

which is present for the icat server, and installs the appropriate pip version

### Steps To Reproduce

1. Environment Centos 7, one host for icat, another for resource server, ansible 2.10
2. Start installation process with the ansible playbook

### Environment

```markdown
- Yoda: 1.8.4
- Ansible: 2.10
- Operating System: Centos 7
- Browser: xx
```

**Comment by stsnel** [comment]
Thanks for the bug report! We can reproduce the issue, have registered it in the internal issue tracker as YDA-5051, and will test the proposed fix.
