### ISSUE TITLE
[BUG] yoda metadata json flagged as non-preferred when copied back from vault

### ISSUE THREAD

**Issue by Danny-dK** [UtrechtUniversity/yoda-ansible#212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a vault package is copied back to the research folder, the yoda-metadata.json within the vault folder (the one copied back) is flagged as non-preferred using the DANS option when checking for compliancy with policy.

### Expected Behavior

Do not flag yoda-metadata.json as non-preferred regardless of whether it was copied back from the vault or not. 

### Steps To Reproduce

Current example visible in https://acc.dgk.yoda.uu.nl within research-danny-test
- create research group folder
- create metadata in that folder using the Yoda metadata form
- submit folder to the vault
- accept the submission
- copy the vault folder back into the research group folder
- check for compliancy with policy using DANS preferred format list
- metadata json is flagged as non-preferred (specifically the one in [research-danny-test[1675772696]]
![image](https://user-images.githubusercontent.com/45395070/217246157-cc37688f-608d-43a3-919c-fe70cbc6d451.png)

### Environment

```markdown
- Yoda: 1.8
```

**Comment by stsnel** [comment]
Thanks for the bug report. We can reproduce the issue and are now tracking it in the internal issue tracker as YDA-5050.
