### ISSUE TITLE
[FEATURE] Improve the behavior of the metadata Save button

### ISSUE THREAD

**Issue by peer35** [UtrechtUniversity/yoda-ansible#216]
#### Is your feature request related to a problem? Please describe.
Users are automatically logged out of the Yoda portal after a period of inactivity. If they get distracted while filling in the metadata form this means they will lose all the data they entered. For this reason users should be encouraged to save often when filling in the form. 
But:
- Clicking the Save button also closes the form. Which means you have to reopen the form to continue.
- You have to scroll to the save button, so even if the form remained open you have to scroll back to the part of the form you were working on. This can be annoying, for example with a long list of contributors. 

#### Describe the solution you'd like
- The Save button should only save the metadata and not close the form, there is already a separate Close button.
- The Save button should have a fixed position on the screen. For example by moving the Save next to the Close button and always keeping the header at the top of the screen when scrolling. 
(this kind of effect: https://www.w3schools.com/bootstrap4/tryit.asp?filename=trybs_navbar_fixed&stacked=h) 

#### Describe alternatives you've considered
I've also opened a ticket at SURF to see if we can increase the time before the user gets logged out.

#### Additional context
-

**Comment by stsnel** [comment]
Thanks for the proposal. We have scheduled the proposed change for discussion at the 14 March datamanager meeting.

**Comment by stsnel** [comment]
The proposal has been approved in the data manager meeting. We have registered it with internal ticket number YDA-5121; target release is 1.9.0.

**Comment by lwesterhof** [comment]
Implemented in https://github.com/UtrechtUniversity/yoda-portal/commit/7ce69f6b1e3ae25d7adbcdfebccf011c87c22fc4
