### ISSUE TITLE
[FEATURE] yoda metadata change related data package title

### ISSUE THREAD

**Issue by Danny-dK** [UtrechtUniversity/yoda-ansible#218]
Within https://yoda.uu.nl/schemas/default-2/metadata.json 
```
 "Related_Datapackage": {
      "title": "Related datapackage",
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "yoda:structure": "subproperties",
        "properties": {
          "Relation_Type": {
            "$ref": "#/definitions/optionsRelationType",
            "title": "Relation type"
          },
```

Could the title be changed to 'Related resource'? We constantly have to explain to users that you can also specify other resources than data in this field.

**Comment by stsnel** [comment]
Thanks for the proposal. We have scheduled the proposed change for discussion at the 14 March datamanager meeting.

**Comment by stsnel** [comment]
The proposal has been accepted in the data manager meeting. We have registered this task in the internal tracker as ticket number  YDA-5120 with target release 1.9.0.

**Comment by lwesterhof** [comment]
Implemented in https://github.com/UtrechtUniversity/yoda-ruleset/commit/f2da0647b0313ba3dcce3c2d6cba55724e65e57c
