### ISSUE TITLE
[FEATURE] Add multiple people to folders at once

### ISSUE THREAD

**Issue by Danny-dK** [UtrechtUniversity/yoda-ansible#233]
#### Is your feature request related to a problem? Please describe.
When needing to add many users (10s to 100s) to existing or non-existing research-groups, they currently need to be added manually. In the past their was a script available at Yoda@UU which read in a csv that then made all available groups and added people to those groups with specified rights.

#### Describe the solution you'd like
An upload feature for group managers in the group manager to create new research groups and add people to those groups using a pre-defined csv format (and when groups already exist, just add the new people to those folders). Or instructions on how to run the created script at UU.

#### Describe alternatives you've considered
Manual one by one addition.

**Comment by stsnel** [comment]
We have implemented CSV imports in the group manager (in the web portal) and plan to release this functionality as a part of Yoda 1.9.0. The internal ticket number for this story is YDA-4700.

The command-line scripts for importing groups / users are already available for Yoda 1.7.x and 1.8.x. They can be found in the [yoda-clienttools repository](https://github.com/utrechtUniversity/yoda-clienttools).  The `yimportgroups` tool creates research groups and adds members to them based on group/user data in a CSV file. The `yensuremembers` tool adds a common list of members to a set of existing groups. Instructions for running these scripts can be found in the README file of the repository. They assume the user is familiar with working with the command-line.

**Comment by Danny-dK** [comment]
I'm not a python user. What are the other requirements for running these tools. I'm assuming the python iRODS api needs to be installed as well? Or will all requirements be installed upon installing `pip3 install --upgrade git+https://github.com/UtrechtUniversity/yoda-clienttools.git` How does one add the credentials of their Yoda to run the tools?

**Comment by stsnel** [comment]
Yes, that's right. If you follow the installation steps in the README, pip will automatically install dependencies, including python-irodsclient.

**Comment by Danny-dK** [comment]
Thanks. I will try.
