### ISSUE TITLE
[FEATURE] Display DOI in Yoda Vault area when dataset is published

### ISSUE THREAD

**Issue by DorienHuijser** [UtrechtUniversity/yoda-ansible#238]
#### Is your feature request related to a problem? Please describe.

When a dataset is published in Yoda, all you see in the Vault is "Published". However, most researchers need to see the DOI to for example put it in a journal article. 
- At the moment you can only find the DOI via https://public.yoda.uu.nl/ which then refers to https://search.datacite.org/repositories/delft.uu where you can search for the dataset and its DOI. 
- Alternatively, probably the DOI will show up here https://catalog.data.uu.nl/ but I suspect that this is not continuously updated?

#### Describe the solution you'd like
It would be a lot more user-friendly for researchers if their DOI is made visible directly in the Vault once the dataset is published. The other metadata such as Title, authors, description, classification, access and license are already visible there. It would be great if the DOI to the public page can be added there as well, so that researchers do not have to search the web to find the DOI of their own dataset.

#### Describe alternatives you've considered
An alternative that is probably easier to implement could be to insert a link to https://search.datacite.org/repositories/delft.uu in the Vault area so that researchers at least know where they can search for their dataset.

**Comment by stsnel** [comment]
The vault interface currently shows the DOI when you press the black information button next to the "Published" status. The button looks like this:

![Schermafbeelding 2023-03-30 om 16 00 20](https://user-images.githubusercontent.com/7748385/228860739-999fe527-c7a8-4d18-b8e9-b1afcdb3e445.png)

Does this address the issue?

**Comment by DorienHuijser** [comment]
Ah I had totally missed that! Can that be included in the [documentation](https://www.uu.nl/en/research/yoda/guide-to-yoda/i-am-using-yoda/publishing-your-data)? At the moment it just says "You will receive the DOI assigned to your data package after publication is approved.". 

If we can add a sentence at the end of that page that says something like "After publication, you can find the DOI and the link to the dataset's landing page in the Vault under the Information icon, or by searching your dataset via https://search.datacite.org/repositories/delft.uu" (or something like that), you can ignore my suggestion.

**Comment by stsnel** [comment]
Thanks for your feedback! We've requested an update of the documentation website, and expect it will be processed within a few work days.
