### ISSUE TITLE
[FEATURE] Search for users partial name

### ISSUE THREAD

**Issue by Danny-dK** [UtrechtUniversity/yoda-ansible#243]
#### Is your feature request related to a problem? Please describe.
Searching for a user within the group manager of the webportal requires the entire user name to be filled in (john.doe@email.com). It doesn't seem possible to search using partial name (john). Of course in iCommands it would be possible using grep, but I would like this in the webportal as well.

#### Describe the solution you'd like
Be able to search for users using partial usernames.

#### Describe alternatives you've considered
iCommands 
`iadmin lu | grep john`

#### Additional context
Yoda@WUR version 1.8

**Comment by lwesterhof** [comment]
I think we have recently added this, will be released with v1.9.0! Does this solve your issue?


https://user-images.githubusercontent.com/29246264/231685001-a9aa5cf2-0443-4d20-bb9e-bd3ccb6a8ffd.mp4

**Comment by Danny-dK** [comment]
As always...awesome
