### ISSUE TITLE
[BUG] Using uppercase letters in category name prevents adding datamanager group

### ISSUE THREAD

**Issue by hbjkoers** [UtrechtUniversity/yoda-ansible#25]
### Bug description
When I create a new category in the Group Manager, and use capitals in the category name, I am not able to create a datamanager group later on.

### Steps to reproduce
- Go to Group Manager
- Click 'Add group' to open modal
- Enter 'TestcatHK' as category name (creating new category with that name)
- Enter 'subcat' as subcategory name
- Enter 'testgroup' as group name (creating a new group called "research-test")
- Click 'Add group'
- Observe group is added as expected - so far so good
- Click 'Add group' again, modal opens up with "TestcatHK" and "subcat" populated
- Click on 'research' to see the drop-down menu next to 'Group name'

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
- See a list of three options: grp-, research-, intake-

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
- See a list with four options: grp-, research-, intake-, datamanager-

I can consistently reproduce the issue with other category names including capitals. It works as expected when using all lowercase.

### Addtional info

**Yoda version:** Yoda release-1.5
**Ansible version:** n/a
**Operating system:** MacOS Catalina, 10.15.7 (19H2)
**Browser:** Chrome Version 86.0.4240.198 (Official Build) (x86_64)

### Screenshots / debug log

![category and group made successfully](https://user-images.githubusercontent.com/71270083/101680338-d503ce80-3a60-11eb-9f47-0191f82fac36.png)
![missing datamanager option](https://user-images.githubusercontent.com/71270083/101680342-d634fb80-3a60-11eb-8043-290aed4aaa35.png)

**Comment by tsmeele** [comment]
Please note that Rodsadmin type users bypass nearly all consistency checks in Yoda to allow them to perform special actions.  We recommend to use rodsuser type users for regular use.


On 9 Dec 2020, at 20:57, hbjkoers <notifications@github.com<mailto:notifications@github.com>> wrote:


Bug description

When I create a new category in the Group Manager, and use capitals in the category name, I am not able to create a datamanager group later on.

Steps to reproduce

  *   Go to Group Manager
  *   Click 'Add group' to open modal
  *   Enter 'TestcatHK' as category name (creating new category with that name)
  *   Enter 'subcat' as subcategory name
  *   Enter 'testgroup' as group name (creating a new group called "research-test")
  *   Click 'Add group'
  *   Observe group is added as expected - so far so good
  *   Click 'Add group' again, modal opens up with "TestcatHK" and "subcat" populated
  *   Click on 'research' to see the drop-down menu next to 'Group name'

Actual result: Describe here what happens after you run the steps above (i.e. the buggy behaviour)

  *   See a list of three options: grp-, research-, intake-

Expected result: Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

  *   See a list with four options: grp-, research-, intake-, datamanager-

I can consistently reproduce the issue with other category names including capitals. It works as expected when using all lowercase.

Addtional info

Yoda version: Yoda release-1.5
Ansible version: n/a
Operating system: MacOS Catalina, 10.15.7 (19H2)
Browser: Chrome Version 86.0.4240.198 (Official Build) (x86_64)

Screenshots / debug log

[category and group made successfully]<https://user-images.githubusercontent.com/71270083/101680338-d503ce80-3a60-11eb-9f47-0191f82fac36.png>
[missing datamanager option]<https://user-images.githubusercontent.com/71270083/101680342-d634fb80-3a60-11eb-8043-290aed4aaa35.png>

**Comment by hbjkoers** [comment]
Thanks for quick reply! I'll try and test tomorrow as a regular rodsuser to confirm.

**Comment by tsmeele** [comment]
As this behavior is related to rodsadmin bypass features, we're closing this issue.
