### ISSUE TITLE
[BUG] Language not shown on landingpage metadata

### ISSUE THREAD

**Issue by peer35** [UtrechtUniversity/yoda-ansible#259]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

A  very minor bug: I noticed the landingpage metadata shows the language field, but it never has a value. Language is a mandatory metadata field, so it always has a value. 

Some examples:
https://public.yoda.uu.nl/science/UU01/OE9JNJ.html
https://public.yoda.uu.nl/science/UU01/U63Z8W.html
https://publication.yoda.vu.nl/full/VU01/IZJOOF.html
https://publication.yoda.vu.nl/full/VU01/QGRC9V.html

Language looks to be correctly set in the DataCite registrations.

### Expected Behavior

The metadata should show the language that was set in the metadata.

### Steps To Reproduce

Publish a new dataset or update an existing publication.

### Environment

```markdown
- Yoda: v1.8
- Ansible:
- Operating System:
- Browser:
```

**Comment by stsnel** [comment]
Thank you for this bug report. The issue has been reproduced and registered in the internal issue tracker as ticket YDA-5208. A fix is to be included in Yoda 1.9.0, with a backport to version 1.8.7

**Comment by stsnel** [comment]
Fix is complete.
