### ISSUE TITLE
[FEATURE] Add search menu at search bar as default

### ISSUE THREAD

**Issue by Danny-dK** [UtrechtUniversity/yoda-ansible#277]
#### Is your feature request related to a problem? Please describe.
Currently in Yoda, the search bar does not display the 'advanced' search options by default. 

<img src='https://github.com/UtrechtUniversity/yoda/assets/45395070/d1b81f20-24bb-417e-b3d3-b68c206c29e3' width='500'>

They only become available after hitting enter (whether or not something was already typed in).

<img src='https://github.com/UtrechtUniversity/yoda/assets/45395070/d2243e77-d15f-46e7-9c8b-9d24be3251c3' width='500'>

#### Describe the solution you'd like
It is slightly inconvenient to first search or hit enter and then being able to select what I want to search for. For example, I often don't want to search by filename, but by foldername. I'd rather first select immediately what I want to search for.

#### Describe alternatives you've considered
No alternatives.

**Comment by stsnel** [comment]
Thanks for the feedback! We have registered this feature request in the internal issue tracker as YDA-5272. Target release: Yoda 1.9.0 (tentative)

**Comment by lwesterhof** [comment]
Implemented in https://github.com/UtrechtUniversity/yoda-portal/commit/b8ad27f7bd382096dd3867488442dd8da9edaad2
