### ISSUE TITLE
[FEATURE] replace name with 'menu'

### ISSUE THREAD

**Issue by Danny-dK** [UtrechtUniversity/yoda-ansible#278]
#### Is your feature request related to a problem? Please describe.
Several users have indicated that they did not realize that the name at the right-top corner was a drop-down menu (even though there is a small arrow visible).
<img src='https://github.com/UtrechtUniversity/yoda/assets/45395070/a8b4018e-a910-4922-9e8f-4525728e162a' width = '700'>

I can imagine that it might be a bit unclear that it is a menu with multiple menu items to select from. 

#### Describe the solution you'd like
Consider replacing the name of the user with the word 'menu' (or something like it).

#### Describe alternatives you've considered
Keep the name but add an icon to clarify it is a menu.

Add the 3-dot menu icon (hamburger menu)
![image](https://github.com/UtrechtUniversity/yoda/assets/45395070/a6c48108-02ee-4368-bdb1-dfa3db3b48af)

or a gear icon
![image](https://github.com/UtrechtUniversity/yoda/assets/45395070/eff7333a-25cc-40ff-94dd-03c7e2ad367c)

Within other web platforms (gmail, outlook), additional menu items or settings are signified with such icons.

**Comment by stsnel** [comment]
We have considered this feature request in the development team. At least for the time being, we are leaning towards keeping the current button text and layout. This button currently uses the default layout of the frontend framework that Yoda's UI is based on, and we are not sure that changing its text and/or icons will result in more users recognizing its purpose. 

Keeping this issue open for comments and feedback.

**Comment by Danny-dK** [comment]
Thanks. Would a simple addition of a gear icon help instead of the current drop-down icon?

**Comment by RobvanSchip** [comment]
For now we will keep the current version of the button text and lay-out. For the next UI overhaul we will discuss this with the UX team.
