### ISSUE TITLE
[BUG] Space at the end of submitted folder breaks Datamanager notification link

### ISSUE THREAD

**Issue by peer35** [UtrechtUniversity/yoda-ansible#282]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

A researcher submits a folder in the research space with a name containing a space at the end.

The Datamanager clicks the notification in the portal and gets a "The given path does not exist error". 

If the DM manually browses to the submitted folder he has access and can approve/reject as normal.

Reason:
The folder URL is:
https://portal.yoda.vu.nl/research/browse?dir=%2Fresearch-beta-alife-freia%2FH295R%20ring%20trial%20phase%20I%20

The Notification widget links to:
https://portal.yoda.vu.nl/research/browse?dir=/research-beta-alife-freia/H295R%20ring%20trial%20phase%20I

Note the missing `%20` at the end, the code probably strips the url.

### Expected Behavior

Clicking on the notification link should lead to the submitted folder.

Although trailing spaces are technically allowed, I would also suggest measures to avoid them:
1. Stripping trailing spaces when creating a folder in the webportal.
2. Maybe implementing an action under the "Action" button to highlight and/or fix names with trailing spaces.

### Steps To Reproduce

As a group user with write access:
- Create a subfolder with a trailing space in the name in any research folder. (portal or webdav).
- Upload some data.
- Fill the mandatory metadata fields.
- Click submit.

  As a datamanager for the category:
  - Browse to notifications.
  - Click the notification.

### Environment

```markdown
- Yoda:1.8 (surf hosted)
- Ansible:
- Operating System: all
- Browser: all
```

**Comment by lwesterhof** [comment]
Thanks for reporting!
