### ISSUE TITLE
[FEATURE] Add metadata form version info to json

### ISSUE THREAD

**Issue by Danny-dK** [UtrechtUniversity/yoda-ansible#300]
I can't seem to find the version of the metadata form within the JSON file. Considering that elements of the metadata form within Yoda may change over time (has so previously), perhaps it would be good to add a version identifier within the metadata JSON itself. Note that I'm not talking about the version field:
![image](https://github.com/UtrechtUniversity/yoda/assets/45395070/358fb3d3-6e1e-489a-b6ea-42e7cd15578d)

As that relates to the version of the datapackage, not the metadata form.

Perhaps even add the datacite standard version as well?

If it is present within the metadata, then assume I'm just blind.

**Comment by stsnel** [comment]
Hi Danny,

The schema version number is currently part of the schema id. For example, `default-3` is version 3 of the Yoda `default` metadata schema. The `id` is listed e.g. here:
 https://github.com/UtrechtUniversity/yoda-ruleset/blob/a781dd81240236d851652b8b01d6ef94ee53b116/schemas/default-3/metadata.json#L2

The internal/regular Yoda metadata file has a different format from the metadata that is transmitted to Datacite, so it does not have a Datacite schema version.

Does this answer your question?

**Comment by Danny-dK** [comment]
Yes, it answers that I am indeed blind (sorry).

The Yoda metadata is based on the Datacite metadata scheme right? https://schema.datacite.org/meta/kernel-4.4/
Perhaps such information could be included in the id? Or are the metadata fields not all from datacite?

**Comment by stsnel** [comment]
No worries.

Yoda internal metadata is indeed transformed to Datacite metadata on publication. However, I don't think there's necessarily a one-to-one relationship between Yoda metadata schemas and Datacite schemas.

If we hard code the Datacite schema in the Yoda metadata, we would be unable to update Yoda to use a new Datacite metadata schema for an existing Yoda metadaat schema (or, alternatively, the hardcoded Datacite schema would no longer be correct).

**Comment by Danny-dK** [comment]
Okay, understand. Thanks!
