### ISSUE TITLE
[FEATURE] Do not allow open licenses when Access is set to Restricted or Closed

### ISSUE THREAD

**Issue by DorienHuijser** [UtrechtUniversity/yoda-ansible#310]
#### Is your feature request related to a problem? Please describe.
In the metadata form in Yoda right now, you can select License and Access conditions independently of each other. However, I do not think it makes sense if:

- A dataset is not publicly available (access conditions set to Restricted or Closed), and
- The license is still an open license, such as the Creative Commons license or the Open database license

Since the license always covers the *data*, and not the metadata (because the metadata is available under CC0 right?), I do not think it makes sense to put an open license on data that is not publicly available. As far as I am aware, the CC licenses are meant for publicly available resources - *but perhaps I am mistaken in this assumption!*

#### Describe the solution you'd like

The metadata form should make sure that when Access is set to Restricted or Closed, the open licenses disappear from the Licenses list.

#### Describe alternatives you've considered

The alternative is to keep things as is. 

#### Additional context

This question arose because, in another project that I'm working on, we are planning to exchange metadata with ODISSEI. The data underlying the metadata is very sensitive and therefore not publicly available. The studies that collected the data all use their own access procedures, and the question arose what license we should apply in this case (ODISSEI does not offer the Custom option - yet?)

**Comment by lwesterhof** [comment]
Good news, we have implemented this in the latest default schema (default-3). This schema will be released together with v1.9. 

When Access is set to Restricted or Closed, Custom is the only license option:

https://github.com/UtrechtUniversity/yoda/assets/29246264/7b6b448d-7207-4f66-84e7-5342d5a9b48e

**Comment by DorienHuijser** [comment]
Ooh I didn't know that, thanks @lwesterhof!
