### ISSUE TITLE
[BUG] case sensitive username comparison between Yoda and SRAM api

### ISSUE THREAD

**Issue by ccacciari** [UtrechtUniversity/yoda-ansible#323]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I promote a user to the group manager role, I get an error: "something went wrong getting the unique user id ..." , even if the user is member of the related SRAM collaboration, as expected. The only visible difference is that the user email address is stored in lower case letters in Yoda and in capital letters in SRAM.

### Expected Behavior

I expect that the unique user id is returned independently from the fact that the username is written in capital or lower case letters.

### Steps To Reproduce

- log in as group manager
- promote another member of the group to the role of group manager
- get a pop-up window reporting an error in getting the unique user id from SRAM
- check the way the username is written in SRAM and in Yoda.

### Environment

```markdown
- Yoda: 1.9 rc1
- Ansible:
- Operating System: CentOS 7
- Browser: firefox 119.0 (64-bit)
```

**Comment by lwesterhof** [comment]
Fixed in https://github.com/UtrechtUniversity/yoda-ruleset/commit/fac2de94350a35d790a04bc53c42a63d9b4d7c41
