### ISSUE TITLE
[BUG] Unable to edit or open metadata in subfolder when subfoldername has space

### ISSUE THREAD

**Issue by Danny-dK** [UtrechtUniversity/yoda-ansible#348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Add a research group. Then add a subfolder in that research group of which the name of that folder has a space. Go in to the subfolder and click on the metadata button in the webportal, get the error

![image](https://github.com/UtrechtUniversity/yoda/assets/45395070/617591fa-2940-4a34-be4f-2e26ce62b3ad)

### Expected Behavior

Be able to open, create, or edit metadata of subfolders even if the subfoldername has a space. Workaround is to rename folder without a space (I know, basic RDM principles, but with many researchers it is very difficult to convey).

### Environment

```markdown
- Yoda: 1.9 rc5
```

**Comment by lwesterhof** [comment]
Fixed in https://github.com/UtrechtUniversity/yoda/pull/351
