### ISSUE TITLE
[FEATURE] update public metadata editor to default-3

### ISSUE THREAD

**Issue by Danny-dK** [UtrechtUniversity/yoda-ansible#349]
No rush / hurry, only when you have time.

Can the https://github.com/UtrechtUniversity/yoda-portal/tree/yoda-metadata-editor be updated to default-3 metadata form?

**Comment by Danny-dK** [comment]
@lwesterhof Even though not a rush, any time-frame for default 3 to be available in public editor? (I tried to change it so I could do pull request, but alas, I'm too dumb and couldn't figure out which files and folders where required)

**Comment by lwesterhof** [comment]
I'll try to squeeze it in next week!

**Comment by lwesterhof** [comment]
Done, let me know if something is broken after the update.

**Comment by lwesterhof** [comment]
Done, let me know if something is broken after the update.

**Comment by Danny-dK** [comment]
@lwesterhof  didn't want to create a new issue, hence here. When uploading a json that was filled in using the metadata editor, the organization and personal affiliation identifiers aren't taken over (everything else is). Probably just a small thing for users to adjust, but if it is possible to take that over when uploading the json, it would be nice. If not, then the intro text would need some slight adjusting to involve 'Note that affiliations need to be entered again if you upload a json.'

**Comment by Danny-dK** [comment]
@lwesterhof In addition to the above, for those fields with '+' actions, there seems to be some icons missing:

![image](https://github.com/UtrechtUniversity/yoda/assets/45395070/0c23e96e-4dd8-4485-8679-19178002a2b9)
