### ISSUE TITLE
[FEATURE] Remove 'secured' status of folder

### ISSUE THREAD

**Issue by lwesterhof** [UtrechtUniversity/yoda-ansible#358]
#### Is your feature request related to a problem? Please describe.

Discussed in https://github.com/UtrechtUniversity/yoda/discussions/165

<div type='discussions-op-text'>

<sup>Originally posted by **Danny-dK** October 18, 2022</sup>
When I submit a folder to the vault and is successfully secured, it gets the label 'secured'.

![image](https://user-images.githubusercontent.com/45395070/196382711-7a99645f-2d51-4279-b89a-af4291f8e2f8.png)

When I add a new file to that folder in the research environment, the label 'secured' remains visible when the current contents are not secured in the vault. Should that label not disappear or specify something in the likes of 'current version not secured' as that specific folder contents is not secured (only a previous version of that folder is secured)?  </div>

#### Describe the solution you'd like
Display the secured label as is, but remove it as soon as data in that folder is modified.

#### Additional context
Originally a folder would still be locked after it was secured in the vault space as a data package. The user had to unlock the folder to start working on it again. This behaviour was later changed and a folder would be automatically unlocked after securing the data in the vault space.

**Comment by stsnel** [comment]
Outcome of data manager meeting of 7 May: we will remove the secured state entirely from the vault workflow

This will simplify the flow, and not having to check for changes in the collection also eliminates a potential source of performance problems for folders with many data objects

**Comment by RobvanSchip** [comment]
Thank you for the feature request. This is planned for version 1.10 and we have registered it in our product backlog as ticket nr. [YDA-5598](https://utrechtuniversity.atlassian.net/browse/YDA-5598)

**Comment by lwesterhof** [comment]
Implemented in https://github.com/UtrechtUniversity/yoda-ruleset/commit/3b943c3f9d86252657f4f55f0fd9754d20aaf03f
