### ISSUE TITLE
[BUG] read-only users are not automatically re-invited via SRAM using the migration script

### ISSUE THREAD

**Issue by ccacciari** [UtrechtUniversity/yoda-ansible#374]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The Yoda read-only users are not migrated to SRAM after executing the SRAM migration procedure.

### Expected Behavior

I would expect that the existing Yoda read-only users receive a new invite via SRAM.

### Environment

```markdown
- Yoda:1.9 RC6
- Ansible:
- Operating System: CentOS 7
- Browser:
```

**Comment by RobvanSchip** [comment]
Thank you for this bug report. The issue has been registered in the internal issue tracker as ticket YDA-5622

**Comment by lwesterhof** [comment]
Fixed in https://github.com/UtrechtUniversity/yoda-ruleset/commit/521d93b8bc10fcc15315d3341dfd662a2965ebd8
