### ISSUE TITLE
[FEATURE] Automatically label SRAM Collaborations created by Yoda

### ISSUE THREAD

**Issue by peer35** [UtrechtUniversity/yoda-ansible#380]
#### Is your feature request related to a problem? Please describe.
Currently SRAM Collaborations created by Yoda are not labelled. This makes filtering harder as an SRAM Organization Admin. 

#### Describe the solution you'd like
Add a standard label to a new SRAM CO on creation. The text should be configurable on setup/upgrade of Yoda, e.g. `yodavu`.
Add an additional label to be able to separate datamanager, research and system COs, e.g. `yodadatamanager`, `yodaresearch`, `yodapriv`

#### Describe alternatives you've considered
- Adding the label by hand. Not feasible for 200+ COs.
- Add the label via the api based on the CO name. Needs to be repeated for every new CO and might mislabel a CO.
- Using the search option to filter by name, too crude.

#### Additional context
Screenshot of our SRAM management portal:
![2024-03-06 11_46_59-SRAM - Vrije Universiteit Amsterdam — Mozilla Firefox](https://github.com/UtrechtUniversity/yoda/assets/5236397/2b816c87-f25a-49fa-945c-49fb231bd372)

**Comment by lwesterhof** [comment]
Implemented in https://github.com/UtrechtUniversity/yoda/commit/868786ec9416b732c461c3a21a8fdf022e0c6564 and https://github.com/UtrechtUniversity/yoda-ruleset/commit/3da4a934f8fd6025f38e26aa39dacf4275b7bb33

Configurable CO label defaults to 'yoda'. Additional label is added with group type.
