### ISSUE TITLE
[BUG] Contributor ORCIDs on landing page are not shown as a clickable links

### ISSUE THREAD

**Issue by peer35** [UtrechtUniversity/yoda-ansible#418]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Not all ORCIDs are shown as clickable links. Looking at the Yoda metadata I see this only happens with contributors, orcids of creators are shown correctly.

See for example the ORCIDs shown on:
https://publication.yoda.vu.nl/full/VU01/11WJKE.html
https://publication.yoda.vu.nl/full/VU01/T0M09U.html

### Expected Behavior

If a person identifier can be shown as a clickable link it should be.

### Steps To Reproduce

Publish a dataset with a Contributor with an orcid as person identifier.

### Environment

```markdown
- Yoda:v1.9.0-rc.6
- Ansible:-
- Operating System:all
- Browser:all
```

### Anything else?

Looks like a small oversight in the template https://github.com/UtrechtUniversity/yoda-ruleset/blob/fdc13977d90c983c03684bc6ea038d50c6f68643/templates/landingpage.html.j2

compare lines 402-410 with 455-457

**Comment by stsnel** [comment]
Thank you for the bug report. We have registered it in our internal bug tracker as ticket nr. YDA-5712

**Comment by lwesterhof** [comment]
Fixed in https://github.com/UtrechtUniversity/yoda-ruleset/commit/77d8a177f79ceb839d6da59c7b0a6a9aa0c7e0a4
