### ISSUE TITLE
[FEATURE] protecting research area collections' acl against mistakes done by normal users, via ichmod

### ISSUE THREAD

**Issue by ccacciari** [UtrechtUniversity/yoda-ansible#45]
#### Is your feature request related to a problem? Please describe.
In our YODA instance a normal user can retract read and write access to all data in his/her group via the icommands. By this a user could hide another user's data from her/him. For example:
`ichmod null research-electronics#yoda iRODS_UGM_2019.pdf`
it will hide the object "iRODS_UGM_2019.pdf" from the members of the research group "research-electronics#yoda".

#### Describe the solution you'd like
Since ACLs are set by YODA and not be changed by normal users can you please inhibit this feature for data that a user did not upload her/himself?

#### Describe alternatives you've considered
It could be possible to close the access to iRODS for normal users, but it seems too restrictive for some use cases.

**Comment by lwesterhof** [comment]
We can probably prevent this with pep_api_mod_access_control_pre and pep_api_mod_access_control_post.

**Comment by lwesterhof** [comment]
Fixed in https://github.com/UtrechtUniversity/yoda-ruleset/pull/359
