### ISSUE TITLE
[BUG] Publication failure due to inconsistent validation of Creator Affiliation

### ISSUE THREAD

**Issue by peer35** [UtrechtUniversity/yoda-ansible#455]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The default-3 metadata form shows the _Creator Affiliation Name_ as mandatory, with asterisk and a red box, and tied to the green "Required for the vault" progress bar. But if you leave the value empty it is still possible to submit the folder for the Vault. 

If that dataset is later submitted and approved for publication the publication process fails and the datasets stays in the "Approved for publication" state. Logs indicate the metadata has failed to validate because of the missing Affiliation (Log details known at SURF SD-80590).

### Expected Behavior

Upon clicking submit in the Research space Yoda should show the standard error message: _Metadata is not valid, please open metadata form for more information_ and not process the submission if a mandatory Creator Affiliation name value is empty.

### Steps To Reproduce

In a group using the default-3 schema:
- Open a new metadata form and fill in the mandatory fields.
- Add at least one Creator and only fill the first and last name.
- Save the form. 
- Notice the green bar shows the form is incomplete.
- Click submit on the folder, the submission process starts normally.
- Approve it as a Datamanager.
- Once the dataset is secured Submit it for Publication and approve it.

### Environment

```markdown
- Yoda v1.9.0-rc6 & Yoda development (2024-07-31)
- Metadata schema default-3
```

**Comment by ccacciari** [comment]
As additional information, here it is the iRODS server log:

Jul 26 16:39:03 pid:24193 NOTICE: writeLine: inString = {rods#yoda} [publication] Running process_publication in verbose mode.
Jul 26 16:39:03 pid:24193 NOTICE: writeLine: inString = {rods#yoda} [publication] Initial publication status is: Unknown
Jul 26 16:39:03 pid:24193 NOTICE: writeLine: inString = {rods#yoda} [publication] Setting publication date.
Jul 26 16:39:03 pid:24193 NOTICE: writeLine: inString = {rods#yoda} [publication] Generating preliminary DOI.
Jul 26 16:39:03 pid:24193 NOTICE: writeLine: inString = {rods#yoda} [publication] Updating modification date.
Jul 26 16:39:03 pid:24193 NOTICE: writeLine: inString = {rods#yoda} [publication] Generating combi JSON.
Jul 26 16:39:03 pid:24193 NOTICE: writeLine: inString = {rods#yoda} [publication] Creating landing page.
Jul 26 16:39:03 pid:24193 NOTICE: writeLine: inString = {rods#yoda} [publication] Generating Datacite JSON.
Jul 26 16:39:03 pid:24193 NOTICE: writeLine: inString = {rods#yoda} [publication] Exception while generating Datacite JSON: 'Affiliation_Name'
Jul 26 16:39:03 pid:24193 NOTICE: writeLine: inString = {rods#yoda} [publication] Error status after generating Datacite JSON: Unrecoverable

**Comment by lwesterhof** [comment]
Thank you for the bug report. We have registered it in our internal bug tracker as ticket [YDA-5859](https://utrechtuniversity.atlassian.net/browse/YDA-5859) .
