### ISSUE TITLE
[BUG] missing revision in a research area folder

### ISSUE THREAD

**Issue by ccacciari** [UtrechtUniversity/yoda-ansible#48]
### Bug description
A user wants to search a revision using the name of the file via web portal UI.
The user has uploaded two different versions of the file, using the same name, but the search result about revisions is empty.
Looking at the revisions folder in iRODS, as irods admin, I confirm that no revision has been created there.
Looking at the iRODS logs no error appears related to a failure of the Yoda rules.

### Steps to reproduce

- Upload a text file with one line of text
- Add one line of text to the file and upload again with the same name
- Add another line and upload again
- "Search by revision" on the name of the text file

**Actual result:** I get "No accessible files/folders present"
**Expected result:** You should find the revisions and be able to restore a revision

### Addtional info

**Yoda version:** v1.7.0
**Operating system:** win 10
**Browser:** Firefox

The bug is tricky to reproduce.
On the same Yoda 1.7 instance I tried with my user to reproduce the error. I managed on the user research folder, but not on a different research folder. The user is able to create correctly revisions on my research folder. So it seems that the folder affects the behaviour of the revisions, but it is not clear why. The user's folder is a normal research area folder, the permissions seem fine, the user is group manager of that group. The folder has not been submitted and it is not locked.
My folder has the same properties: I am group manager, the folder is not locked and has not been submitted, but both I and the user are able to create revisions for files in my folder. Both fail to do the same in the user's research folder.

**Comment by lwesterhof** [comment]
Not reproducible, everything seems to work fine after the upgrade to 1.7
