### ISSUE TITLE
incorrect path to `irods_environment.json` in icat deployment role

### ISSUE THREAD

**Issue by kript** [UtrechtUniversity/yoda-ansible#66]
According to;

https://github.com/UtrechtUniversity/yoda/blob/5fcdde09b2fffe62736107e828f3f8e8c5f5fa05/roles/irods_icat/tasks/main.yml#L217

(on the `/release-1.7` branch)
the check for iRODS being setup looks for the local user's environment file.  However on deployment, the ansible gives

```
TASK [irods_icat : Ensure iRODS host is defined] ***********************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: IOError: [Errno 2] No such file or directory: '/var/lib/irods/.irods/irods_environment.json'
fatal: [irods-yoda-ies-01.internal.sanger.ac.uk]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_irods_config_payload_yNZTSk/ansible_irods_config_payload.zip/ansible/modules/irods_config.py\", line 60, in <module>\n  File \"/tmp/ansible_irods_config_payload_yNZTSk/ansible_irods_config_payload.zip/ansible/modules/irods_config.py\", line 31, in main\nIOError: [Errno 2] No such file or directory: '/var/lib/irods/.irods/irods_environment.json'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

when I log onto the server and check I see the homedir is in fact elsewhere;

````
[irods@irods-yoda-ies-01 ~]$ ienv | grep irods_environment_file
irods_environment_file - /usr/local/iRODS/.irods/irods_environment.json
````

Have I missed/misunderstood something?

This was deployed using the 'full' development deployment option.

**Comment by lwesterhof** [comment]
On what OS are you deploying?

**Comment by kript** [comment]
We deployed 1.5 (I think) using Vagrant, so that was `CentOS Linux release 7.8.2003 (Core)`, but with 1.7 we used `CentOS Linux release 7.9.2009 (Core)`

**Comment by stsnel** [comment]
I am unable to reproduce this issue with a clean CentOS 7.9 VM (bento/centos7.9 Vagrant box, with the development branch of Yoda at commit d3cca8050db, and default allinone development configuration).

However, IIRC, i have seen a similar issue before when Yoda was deployed on a server that had a pre-existing irods account with a nonstandard home directory. Is it possible that this caused the issue in your case, John? In that case, the quickest solution would be to re-deploy the server with a clean CentOS image; then install Yoda again using Ansible.

**Comment by kript** [comment]
🤦‍♀️ yes that’s exactly the issue! I am frankly 😊 that I didn’t think of that! I’ll override locally, thanks!
