### ISSUE TITLE
[FEATURE] For EUA make 'domain' variable

### ISSUE THREAD

**Issue by mkorthof** [UtrechtUniversity/yoda-ansible#87]
#### Is your feature request related to a problem? Please describe.

Please make the user's 'domain' variable instead of uu.nl.

#### Describe the solution you'd like

In /usr/local/bin/is-user-external.sh  this already is done by var external_users_domain_filter

`[[ "$PAM_USER" =~ .*@.* ]]`

However, in irods-ruleset-uu/uuGroup.r the domain is static so we change it:

```
- if (*domain != "uu.nl" && *domain not like "*.uu.nl") {
+ if (*domain != "") {
```

#### Describe alternatives you've considered

Currently we have to make the change above on every deployment.

#### Additional context

Ex. *Here's a photo of my cat!*

**Comment by stsnel** [comment]
Thanks for the report. We're tracking this issue in our internal bug tracker as ticket YDA-4373

**Comment by ccacciari** [comment]
This is the change I needed to apply to /etc/irods/rules-uu.re in order to make it working as wanted:

    uuExternalUser(*userName) {
            *domainList = list("mydomain1.nl","mydomain2.nl","mydomain3.nl","mydomain4.nl");
            *nameAndDomain = split(*userName, "@");
            if (size(*nameAndDomain) == 2) {
                    *domain = elem(*nameAndDomain, 1);
                    uuListContains(*domainList, *domain, *inList);
                    *inListRegex = false;
                    foreach (*item in *domainList) {
                        if (*domain like "*.*item") {
                            *inListRegex = true;
                            break;
                        }
                    }
                    if (!(*inList) && !(*inListRegex)) {
                            true;
                    } else {
                            false;
                    }
            } else {
                    false;
            }
    }
