### ISSUE TITLE
[BUG] Can't fill in (Sub)Category in Group Manager

### ISSUE THREAD

**Issue by mk-surf** [UtrechtUniversity/yoda-ansible#99]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After selecting Add Group, Sub(Category) textfield cannot be edited

### Expected Behavior

Being able to fill in (sub)category in the text field.

### Steps To Reproduce

Goto:
- Group Manager
- Add Group
- Sub(Category)
- Textfield cannot be edited (inside the dropdown)

Copy/paste does work, and so does selecting an existing Category

### Environment

```markdown
Yoda 1.8b1
Latest Firefox/Chrome/Chromium
Latest Fedora Linux, MacOS
Tested by 2 users/pc's
```

### Anything else?

Screenshot:
![Screenshot 2022-01-19 at 11 18 05](https://user-images.githubusercontent.com/88498634/150111313-bd6324bc-5954-475c-a834-ebf42e414f3f.png)

JS error in dev tools console:
```
Uncaught TypeError: $group.parents(...).children(...).collapse is not a function
    unfoldToGroup https://example-yoda.irods.surfsara.nl/group_manager/assets/js/group_manager.js:232
    load https://example-yoda.irods.surfsara.nl/group_manager/assets/js/group_manager.js:1514
    <anonymous> https://example-yoda.irods.surfsara.nl/group_manager/:37
group_manager.js:232:66
```

[#L232](https://github.com/UtrechtUniversity/yoda-portal/blob/e8e037b734751b8f8344166cc6e843850c5cd2de/group_manager/static/group_manager/js/group_manager.js#L232): $group.parents('.category').children('.category-ul').**_collapse_**('show');

Putting '`<script src=bootstrap.js>`' on top/before jquery makes the JS error disappear but the text field can still not be edited

**Comment by lwesterhof** [comment]
Tracking internally as YDA-4491.
